<h1>Szczegóły książki</h1>

<div class="row">
    <div class="col-lg-4">
            <h4>ID<br /></h4>
            <?= $this->ksiazka->id ?><br />
            <h4>Tytuł<br /></h4>
            <?= $this->ksiazka->tytul ?><br />
            <h4>Opis<br /></h4>
            <?= $this->ksiazka->opis ?><br />
            <h4>Cena<br /></h4>
            <?= $this->ksiazka->cena ?><br />
            <h4>Liczba Stron<br /></h4>
            <?= $this->ksiazka->liczba_stron ?>

    </div>
</div>